id: P000722
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:39:02.072836
source_metadata:
  id: bdr:W1KG25602
  title: ཡིག་གཟུགས་མཐོང་བ་དགའ་སྐྱེད་།
  author: ''
  volumes:
    01d805b7cc6c4a8689a513ddcea2b31a:
      image_group_id: I1KG25604
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
