id: I2BBFAFB1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T00:48:07+00:00'
last_modified: '2022-06-07T12:45:04.953408+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25602
  title: ཡིག་གཟུགས་མཐོང་བ་དགའ་སྐྱེད་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    E197:
      image_group_id: I1KG25604
      title: ''
      total_pages: 146
      order: 1
      base_file: E197.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
